default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: serbia11
  host: localhost

development:
  <<: *default
  database: activity_12_01_development

test:
  <<: *default
  database: activity_12_01_test

production:
  <<: *default
  database: activity_12_01_production


